### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [retrodaredevil/track-shooter#3]
Hi,

Since this app is Apache v2 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by retrodaredevil** [comment]
Thanks for the suggestion. I would definitely like to have track-shooter on f-droid.

Right now, I don't think I'm willing to try to figure out how to get the app included on f-droid, so I would be fine if someone else was willing to do it for me.

The only thing I think we would have to collaborate on would be the SHA1 key that is used to sign the app. For the Google Play Store I use their signing process, so for F-Droid we could use a different key. I would use the SHA1 key to correctly authorize people who want to sign in with Google to get the features that come with Google Play Games Services.

If there's anything I can do to help, let me know. Thanks for reaching out.

**Comment by Poussinou** [comment]
According to your gradle you're using proprietary dependencies such as the ones for google play (I didn't saw that before). It won be possible to add this game to F-Droid, unless we have a different build flavor without them. Also, we need to build all binaries directly from source, sounds like a difficult thing here.

**Comment by retrodaredevil** [comment]
I might be able to eventually work on creating that build flavor, but I think I'd also have to create a separate module as well. (Since I can't import google play games services stuff at all in the same module)

Luckily the game is mostly set up to have plug and play components so once the imports are working, it shouldn't be too difficult. I also left the master branch in an uncomplete state, which I have to fix.

I'll probably eventually get around to doing some of these things, but I want to start and mostly finish a new project by the end of this year so I have no idea when I'll get around to this project.

I'd definitely like to have my game on F-Droid, but I think it'll have to wait for a little while until I can figure out a few things.

**Comment by retrodaredevil** [comment]
@Poussinou I started working on a refactor to have a version without proprietary google libraries in it. I believe the `appbasic` module should be able to be uploaded to F-Droid now. I'm going to make some changes in the next few days, then it should be ready.

Let me know if you're still able to help get this uploaded to F-Droid. If not I might try to do it myself, I'm not sure yet.
